name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Prepare node and yarn
        uses: volta-cli/action@v1

      - name: Install packages, test, and build
        run: |
          pwd
          node --version
          yarn --version
          yarn
          yarn lint
          yarn build
        env:
          CI: true

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tojurnru/poe-guild-ranking-bot:latest
